# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visaUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectedTestLabel = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectedTestLabel.setFont(font)
        self.selectedTestLabel.setObjectName("selectedTestLabel")
        self.horizontalLayout_2.addWidget(self.selectedTestLabel)
        self.chooseFolder = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chooseFolder.setFont(font)
        self.chooseFolder.setObjectName("chooseFolder")
        self.horizontalLayout_2.addWidget(self.chooseFolder)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.globalTestButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.globalTestButton.setFont(font)
        self.globalTestButton.setObjectName("globalTestButton")
        self.verticalLayout_3.addWidget(self.globalTestButton)
        self.globalProgressLabel = QtWidgets.QLabel(self.tab)
        self.globalProgressLabel.setEnabled(True)
        self.globalProgressLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.globalProgressLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.globalProgressLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.globalProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.globalProgressLabel.setHidden(True)
        self.globalProgressLabel.setObjectName("globalProgressLabel")
        self.verticalLayout_3.addWidget(self.globalProgressLabel, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.singleTestButton = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.singleTestButton.setFont(font)
        self.singleTestButton.setObjectName("singleTestButton")
        self.verticalLayout_5.addWidget(self.singleTestButton)
        self.singleProgressLabel = QtWidgets.QLabel(self.frame_3)
        self.singleProgressLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.singleProgressLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.singleProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.singleProgressLabel.setHidden(True)
        self.singleProgressLabel.setObjectName("singleProgressLabel")
        self.verticalLayout_5.addWidget(self.singleProgressLabel, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.posamicniTestiLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.posamicniTestiLabel.setFont(font)
        self.posamicniTestiLabel.setObjectName("posamicniTestiLabel")
        self.horizontalLayout_3.addWidget(self.posamicniTestiLabel)
        self.loadTests = QtWidgets.QPushButton(self.frame_6)
        self.loadTests.setObjectName("loadTests")
        self.horizontalLayout_3.addWidget(self.loadTests)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.searchBox = QtWidgets.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchBox.setFont(font)
        self.searchBox.setObjectName("searchBox")
        self.verticalLayout_6.addWidget(self.searchBox)
        self.posamicniTestiListWidget = QtWidgets.QListWidget(self.frame_4)
        self.posamicniTestiListWidget.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.posamicniTestiListWidget.setFont(font)
        self.posamicniTestiListWidget.setObjectName("posamicniTestiListWidget")
        self.verticalLayout_6.addWidget(self.posamicniTestiListWidget)
        self.selectAllCheckBoxesButton = QtWidgets.QPushButton(self.frame_4)
        self.selectAllCheckBoxesButton.setMinimumSize(QtCore.QSize(50, 0))
        self.selectAllCheckBoxesButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.selectAllCheckBoxesButton.setObjectName("selectAllCheckBoxesButton")
        self.verticalLayout_6.addWidget(self.selectAllCheckBoxesButton)
        self.horizontalLayout.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.izpisLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(True)
        self.izpisLabel.setFont(font)
        self.izpisLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.izpisLabel.setAutoFillBackground(False)
        self.izpisLabel.setScaledContents(True)
        self.izpisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.izpisLabel.setWordWrap(False)
        self.izpisLabel.setObjectName("izpisLabel")
        self.verticalLayout.addWidget(self.izpisLabel)
        self.failOkLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.failOkLabel.setFont(font)
        self.failOkLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.failOkLabel.setAutoFillBackground(False)
        self.failOkLabel.setScaledContents(True)
        self.failOkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.failOkLabel.setWordWrap(False)
        self.failOkLabel.setObjectName("failOkLabel")
        self.verticalLayout.addWidget(self.failOkLabel)
        self.neuspeliTestiLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.neuspeliTestiLabel.setFont(font)
        self.neuspeliTestiLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.neuspeliTestiLabel.setAutoFillBackground(False)
        self.neuspeliTestiLabel.setScaledContents(True)
        self.neuspeliTestiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.neuspeliTestiLabel.setWordWrap(False)
        self.neuspeliTestiLabel.setObjectName("neuspeliTestiLabel")
        self.verticalLayout.addWidget(self.neuspeliTestiLabel)
        self.badTestsListView = QtWidgets.QListWidget(self.frame_2)
        self.badTestsListView.setEnabled(True)
        self.badTestsListView.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.badTestsListView.setFont(font)
        self.badTestsListView.setObjectName("badTestsListView")
        self.verticalLayout.addWidget(self.badTestsListView)
        self.verticalLayout_4.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.globalTestButton.clicked.connect(self.globalTestButtonClicked)
        self.singleTestButton.clicked.connect(self.singleTestButtonClicked)
        self.searchBox.textEdited['QString'].connect(self.searchTextChanged)
        self.posamicniTestiListWidget.itemChanged['QListWidgetItem*'].connect(self.checkBoxSelected)
        self.chooseFolder.clicked.connect(self.chooseFolderButtonClicked)
        self.badTestsListView.itemDoubleClicked['QListWidgetItem*'].connect(self.badTestsListViewItemClicked)
        self.loadTests.clicked.connect(self.loadTestsButton)
        self.selectAllCheckBoxesButton.clicked.connect(self.selectAllCheckboxesButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Unittest GUI"))
        self.selectedTestLabel.setText(_translate("MainWindow", "Mapa ni izbrana !"))
        self.chooseFolder.setText(_translate("MainWindow", "Izberi mapo"))
        self.globalTestButton.setText(_translate("MainWindow", "Zaženi globalni test"))
        self.globalProgressLabel.setText(_translate("MainWindow", ""))#textlabel
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Globalni test"))
        self.singleTestButton.setText(_translate("MainWindow", "Zaženi posamične teste"))
        self.singleProgressLabel.setText(_translate("MainWindow", "")) #textlabel
        self.posamicniTestiLabel.setText(_translate("MainWindow", "Izberi posamične teste:"))
        self.loadTests.setText(_translate("MainWindow", "Naloži teste"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Išči..."))
        self.selectAllCheckBoxesButton.setText(_translate("MainWindow", "Izberi vse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Posamični test"))
        self.izpisLabel.setText(_translate("MainWindow", "Izpis"))
        self.failOkLabel.setText(_translate("MainWindow", "/"))
        self.neuspeliTestiLabel.setText(_translate("MainWindow", "Neuspeli testi:"))

    @pyqtSlot()
    def singleTestButtonClicked(self):
        pass

    @pyqtSlot()
    def globalTestButtonClicked(self):
        pass

    @pyqtSlot()
    def chooseFolderButtonClicked(self):
        pass

    @pyqtSlot()
    def selectAllCheckboxesButtonClicked(self):
        pass

    @pyqtSlot()
    def badTestsListViewItemClicked(self, item):
        pass

    @pyqtSlot()
    def loadTestsButton(self):
        pass

    @pyqtSlot()
    def searchTextChanged(self):
        pass

    @pyqtSlot()
    def checkBoxSelected(self):
        pass
